name: ipfs_client_flutter
description: Built on top of HTTP RPC API.
version: 1.0.5
homepage: https://github.com/raviganwal/ipfs_client_flutter.git

environment:
  sdk: '>=2.16.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_web_compilers:
dependencies: 
  dio: ^4.0.4
